---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: dsm-client

spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsm-client

  template:
    metadata:
      labels:
        app: dsm-client

    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true

      containers:
        - name: dsm-client
          image: IMAGE

          ports:
            - name: http
              containerPort: 8080

          resources:
            limits:
              cpu: 100m
              memory: 32Mi
            requests:
              cpu: 5m
              memory: 32Mi

          livenessProbe:
            tcpSocket:
              port: http

          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
